import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import {
	AppBar,
	Box,
	Container,
	CssBaseline,
	Grid,
	Toolbar,
	IconButton,
	ThemeProvider,
	Typography,
	Button,
} from "@mui/material";
import { MenuBookSharp } from "@mui/icons-material";

import DarkTheme from "../src/themes/darkTheme";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>টাউট দোকান (Taut Dokan)</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<CssBaseline />
			<ThemeProvider theme={DarkTheme}>
				<Container component="main" disableGutters maxWidth={false}>
					<AppBar position="static">
						<Toolbar
							sx={{
								justifyContent: "space-between",
							}}
						>
							<div className="flex">
								<IconButton size="medium" edge="start">
									<MenuBookSharp />
								</IconButton>
								<Typography
									variant="h6"
									sx={{
										padding: "1rem",
										fontWeight: 600,
									}}
								>
									টাউট দোকান
								</Typography>
							</div>
							<Link href="/api/auth/signin">
								<Button>Sign In</Button>
							</Link>
						</Toolbar>
					</AppBar>
					<Grid
						container
						alignItems="center"
						justifyContent="center"
						justifyItems="center"
					>
						<Grid item>
							<Box
								color="primary"
								sx={{
									margin: "10px",
									padding: "5px",
								}}
							></Box>
						</Grid>
					</Grid>
				</Container>
			</ThemeProvider>
		</div>
	);
};

export default Home;
